var searchData=
[
  ['d_20esame_0',['Regole d&apos;esame',['../md_README.html#autotoc_md12',1,'']]],
  ['d_20esame_20indicazioni_20generali_20e_20suggerimenti_20consegne_20per_20gli_20esercizi_1',['Laboratorio per il corso di Algoritmi e Strutture Dati: regole d&apos;esame, indicazioni generali e suggerimenti, consegne per gli esercizi',['../md_README.html',1,'']]],
  ['dati_2',['Uso di Git per il laboratorio di Algoritmi e Strutture Dati',['../md_Git.html',1,'']]],
  ['dati_20grafo_3',['Uso della libreria che implementa la struttura dati Grafo',['..//home/federico/ProgettoAlgoritmiStruttureDati/laboratorio-algoritmi-2024-2025/README.md#autotoc_md48',1,'']]],
  ['dati_3a_20regole_20d_20esame_20indicazioni_20generali_20e_20suggerimenti_20consegne_20per_20gli_20esercizi_4',['Laboratorio per il corso di Algoritmi e Strutture Dati: regole d&apos;esame, indicazioni generali e suggerimenti, consegne per gli esercizi',['../md_README.html',1,'']]],
  ['dei_20conflitti_5',['Risoluzione dei conflitti',['../md_Git.html#autotoc_md10',1,'']]],
  ['del_20linguaggio_20scelto_6',['Uso di librerie esterne e/o native del linguaggio scelto',['../md_README.html#autotoc_md23',1,'']]],
  ['del_20progetto_7',['del progetto',['../md_Git.html#autotoc_md8',1,'Aggiornamento della propria versione del progetto'],['../md_Git.html#autotoc_md6',1,'Clonazione del progetto']]],
  ['del_20progetto_20e_20discussione_20orale_8',['Consegna del progetto e discussione orale',['../md_README.html#autotoc_md17',1,'']]],
  ['dell_20implementazione_9',['Qualità dell&apos;implementazione',['../md_README.html#autotoc_md26',1,'']]],
  ['della_20libreria_20che_20implementa_20la_20struttura_20dati_20grafo_10',['Uso della libreria che implementa la struttura dati Grafo',['..//home/federico/ProgettoAlgoritmiStruttureDati/laboratorio-algoritmi-2024-2025/README.md#autotoc_md48',1,'']]],
  ['della_20libreria_20di_20ordinamento_20implementata_11',['Uso della libreria di ordinamento implementata',['../md_README.html#autotoc_md31',1,'']]],
  ['della_20propria_20versione_20del_20progetto_12',['Aggiornamento della propria versione del progetto',['../md_Git.html#autotoc_md8',1,'']]],
  ['delle_20funzioni_20implementate_13',['Uso delle funzioni implementate',['..//home/federico/ProgettoAlgoritmiStruttureDati/laboratorio-algoritmi-2024-2025/README.md#autotoc_md36',1,'']]],
  ['di_209_20cfu_14',['Studenti e studentesse con Algoritmi non di 9 CFU',['../md_README.html#autotoc_md14',1,'']]],
  ['di_20algoritmi_20e_20strutture_20dati_3a_20regole_20d_20esame_20indicazioni_20generali_20e_20suggerimenti_20consegne_20per_20gli_20esercizi_15',['Laboratorio per il corso di Algoritmi e Strutture Dati: regole d&apos;esame, indicazioni generali e suggerimenti, consegne per gli esercizi',['../md_README.html',1,'']]],
  ['di_20algoritmi_20faqs_16',['Laboratorio di Algoritmi - FAQs',['../md_FAQ.html',1,'']]],
  ['di_20anni_20precedenti_20il_202024_202025_17',['Studenti e studentesse di anni precedenti il 2024/2025',['../md_README.html#autotoc_md13',1,'']]],
  ['di_20base_20per_20lavorare_18',['Comandi di base per lavorare',['../md_Git.html#autotoc_md7',1,'']]],
  ['di_20git_19',['Uso di Git',['../md_README.html#autotoc_md19',1,'']]],
  ['di_20git_20per_20il_20laboratorio_20di_20algoritmi_20e_20strutture_20dati_20',['Uso di Git per il laboratorio di Algoritmi e Strutture Dati',['../md_Git.html',1,'']]],
  ['di_20laboratorio_20e_20turni_21',['Gruppi di laboratorio e turni',['../md_README.html#autotoc_md15',1,'']]],
  ['di_20librerie_20esterne_20e_20o_20native_20del_20linguaggio_20scelto_22',['Uso di librerie esterne e/o native del linguaggio scelto',['../md_README.html#autotoc_md23',1,'']]],
  ['di_20ordinamento_20implementata_23',['Uso della libreria di ordinamento implementata',['../md_README.html#autotoc_md31',1,'']]],
  ['di_20sistema_20basato_20su_20un_20large_20language_20model_3a_24',['Uso di sistema basato su un Large Language Model:',['..//home/federico/ProgettoAlgoritmiStruttureDati/laboratorio-algoritmi-2024-2025/README.md#autotoc_md43',1,'']]],
  ['dijkstra_25',['Accesso via ssh (laboratorio Dijkstra)',['../md_Git.html#autotoc_md4',1,'']]],
  ['dijkstra_20e_20von_20neumann_26',['Accesso via https (laboratorio Dijkstra e Von Neumann)',['../md_Git.html#autotoc_md5',1,'']]],
  ['discussione_20orale_27',['Consegna del progetto e discussione orale',['../md_README.html#autotoc_md17',1,'']]],
  ['distance_28',['Esercizio 2 - Edit distance',['../md_README.html#autotoc_md33',1,'']]]
];
